"""
Serializers for Hello model.
Proto classes will be auto-generated by DSG's generateproto command.
"""
from django_socio_grpc import proto_serializers
from .models import Hello
from application.grpc.hello_app_pb2 import HelloResponse, HelloListResponse


class HelloProtoSerializer(proto_serializers.ModelProtoSerializer):
    """
    Serializer for Hello model that converts model instances to protobuf messages.
    DSG will auto-generate the proto classes when you run: python manage.py generateproto
    """
    
    class Meta:
        model = Hello
        fields = ["id", "message", "location", "properties_key"]
        proto_class = HelloResponse
        proto_class_list = HelloListResponse


