# Generated by Django 5.2.7 on 2025-11-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalspherespatialdata',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
