# Generated by Django 5.2.7 on 2025-11-10 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notes', '0002_mentalspherespatialdata_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindSpatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('rotation', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('scale', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
