# Generated by Django 4.2.25 on 2025-11-02 13:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(dim=3, help_text='3D point location', srid=4326)),
                ('properties_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'hello',
                'ordering': ['-id'],
            },
        ),
    ]
