# Generated by Django 5.2.7 on 2025-10-31 06:59

import app_api.digitalhomes.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', app_api.digitalhomes.models.PointZMField(dim=4, srid=4979)),
                ('rotation', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('scale', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4979)),
                ('boundary', models.JSONField(default=dict)),
            ],
        ),
    ]
