# Generated by Django 5.2.7 on 2025-10-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalhomes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpatialData',
            new_name='HomeSpatialData',
        ),
    ]
