# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello_app/grpc/hello_app.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello_app/grpc/hello_app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ehello_app/grpc/hello_app.proto\x12\x16test_project.hello_app\x1a\x1bgoogle/protobuf/empty.proto\"!\n\x13HelloDestroyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x12\n\x10HelloListRequest\"K\n\x11HelloListResponse\x12\x36\n\x07results\x18\x01 \x03(\x0b\x32%.test_project.hello_app.HelloResponse\"\xa6\x01\n\x19HelloPartialUpdateRequest\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x1b\n\x0eproperties_key\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1e\n\x16_partial_update_fields\x18\x05 \x03(\tB\x05\n\x03_idB\x11\n\x0f_properties_key\"y\n\x0cHelloRequest\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x1b\n\x0eproperties_key\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x11\n\x0f_properties_key\"z\n\rHelloResponse\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x1b\n\x0eproperties_key\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x11\n\x0f_properties_key\"\"\n\x14HelloRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xc4\x04\n\x0fHelloController\x12W\n\x06\x43reate\x12$.test_project.hello_app.HelloRequest\x1a%.test_project.hello_app.HelloResponse\"\x00\x12P\n\x07\x44\x65stroy\x12+.test_project.hello_app.HelloDestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12]\n\x04List\x12(.test_project.hello_app.HelloListRequest\x1a).test_project.hello_app.HelloListResponse\"\x00\x12k\n\rPartialUpdate\x12\x31.test_project.hello_app.HelloPartialUpdateRequest\x1a%.test_project.hello_app.HelloResponse\"\x00\x12\x61\n\x08Retrieve\x12,.test_project.hello_app.HelloRetrieveRequest\x1a%.test_project.hello_app.HelloResponse\"\x00\x12W\n\x06Update\x12$.test_project.hello_app.HelloRequest\x1a%.test_project.hello_app.HelloResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_app.grpc.hello_app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLODESTROYREQUEST']._serialized_start=87
  _globals['_HELLODESTROYREQUEST']._serialized_end=120
  _globals['_HELLOLISTREQUEST']._serialized_start=122
  _globals['_HELLOLISTREQUEST']._serialized_end=140
  _globals['_HELLOLISTRESPONSE']._serialized_start=142
  _globals['_HELLOLISTRESPONSE']._serialized_end=217
  _globals['_HELLOPARTIALUPDATEREQUEST']._serialized_start=220
  _globals['_HELLOPARTIALUPDATEREQUEST']._serialized_end=386
  _globals['_HELLOREQUEST']._serialized_start=388
  _globals['_HELLOREQUEST']._serialized_end=509
  _globals['_HELLORESPONSE']._serialized_start=511
  _globals['_HELLORESPONSE']._serialized_end=633
  _globals['_HELLORETRIEVEREQUEST']._serialized_start=635
  _globals['_HELLORETRIEVEREQUEST']._serialized_end=669
  _globals['_HELLOCONTROLLER']._serialized_start=672
  _globals['_HELLOCONTROLLER']._serialized_end=1252
# @@protoc_insertion_point(module_scope)
