# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hello_app.grpc import hello_app_pb2 as hello__app_dot_grpc_dot_hello__app__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hello_app/grpc/hello_app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HelloControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/test_project.hello_app.HelloController/Create',
                request_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloRequest.SerializeToString,
                response_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/test_project.hello_app.HelloController/Destroy',
                request_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/test_project.hello_app.HelloController/List',
                request_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloListRequest.SerializeToString,
                response_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/test_project.hello_app.HelloController/PartialUpdate',
                request_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloPartialUpdateRequest.SerializeToString,
                response_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/test_project.hello_app.HelloController/Retrieve',
                request_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloRetrieveRequest.SerializeToString,
                response_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/test_project.hello_app.HelloController/Update',
                request_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloRequest.SerializeToString,
                response_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
                _registered_method=True)


class HelloControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloRequest.FromString,
                    response_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloListRequest.FromString,
                    response_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloPartialUpdateRequest.FromString,
                    response_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloRetrieveRequest.FromString,
                    response_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloRequest.FromString,
                    response_serializer=hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test_project.hello_app.HelloController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('test_project.hello_app.HelloController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelloController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_project.hello_app.HelloController/Create',
            hello__app_dot_grpc_dot_hello__app__pb2.HelloRequest.SerializeToString,
            hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_project.hello_app.HelloController/Destroy',
            hello__app_dot_grpc_dot_hello__app__pb2.HelloDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_project.hello_app.HelloController/List',
            hello__app_dot_grpc_dot_hello__app__pb2.HelloListRequest.SerializeToString,
            hello__app_dot_grpc_dot_hello__app__pb2.HelloListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_project.hello_app.HelloController/PartialUpdate',
            hello__app_dot_grpc_dot_hello__app__pb2.HelloPartialUpdateRequest.SerializeToString,
            hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_project.hello_app.HelloController/Retrieve',
            hello__app_dot_grpc_dot_hello__app__pb2.HelloRetrieveRequest.SerializeToString,
            hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_project.hello_app.HelloController/Update',
            hello__app_dot_grpc_dot_hello__app__pb2.HelloRequest.SerializeToString,
            hello__app_dot_grpc_dot_hello__app__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
